parameters:
#    pct_core_user.example.class: PCT\Core\UserBundle\Example

services:
#    pct_core_user.example:
#        class: %pct_core_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
