parameters:
#    pct_core_content.example.class: PCT\Core\ContentBundle\Example

services:
#    pct_core_content.example:
#        class: %pct_core_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
