parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     tuwih
    database_user:     tuwih
    database_password: chuBacca99

    mailer
    _transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            doej9823jd98jrf39f4nj43hj9f843
