pct_core_geo:
    resource: "@PCTCoreGeoBundle/Resources/config/routing.yml"
    prefix:   /api/geo

pct_core_content:
    resource: "@PCTCoreContentBundle/Resources/config/routing.yml"
    prefix:   /api/content

pct_core_comment:
    resource: "@PCTCoreCommentBundle/Resources/config/routing.yml"
    prefix:   /api/comment

pct_core_history:
    resource: "@PCTCoreHistoryBundle/Resources/config/routing.yml"
    prefix:   /api/history

pct_core_user:
    resource: "@PCTCoreUserBundle/Resources/config/routing.yml"
    prefix:   /api/user

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

## Rutas para fos user, no las usamos porque es una api...
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
#
## Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
