parameters:
#    pct_core_comment.example.class: PCT\Core\CommentBundle\Example

services:
#    pct_core_comment.example:
#        class: %pct_core_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
