parameters:
#    pct_core_geo.example.class: PCT\Core\GeoBundle\Example

services:
#    pct_core_geo.example:
#        class: %pct_core_geo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
